CREATE TABLE usuarios (
                          id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome      VARCHAR2(100)  NOT NULL,
                          email     VARCHAR2(100)  NOT NULL UNIQUE,
                          senha     VARCHAR2(255)  NOT NULL,
                          role      VARCHAR2(30)   NOT NULL,
                          cep       VARCHAR2(9),
                          rua       VARCHAR2(150),
                          bairro    VARCHAR2(100)
);

CREATE TABLE categorias (
                            id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE restaurantes (
                              id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              nome       VARCHAR2(100) NOT NULL,
                              descricao  VARCHAR2(255),
                              categoria  VARCHAR2(100),
                              imagem_url VARCHAR2(500),
                              dono_id    NUMBER NOT NULL,
                              CONSTRAINT fk_restaurante_dono FOREIGN KEY (dono_id) REFERENCES usuarios(id)
);

CREATE TABLE produtos (
                          id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome           VARCHAR2(100)  NOT NULL,
                          descricao      VARCHAR2(255),
                          preco          NUMBER(10, 2)  NOT NULL,
                          imagem_url     VARCHAR2(500),
                          categoria_id   NUMBER NOT NULL,
                          restaurante_id NUMBER NOT NULL,
                          CONSTRAINT fk_produto_categoria   FOREIGN KEY (categoria_id)   REFERENCES categorias(id),
                          CONSTRAINT fk_produto_restaurante FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
);

CREATE TABLE pedidos (
                         id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         cliente_id     NUMBER        NOT NULL,
                         restaurante_id NUMBER        NOT NULL,
                         total          NUMBER(10, 2) NOT NULL,
                         status         VARCHAR2(30)  NOT NULL,
                         criado_em      TIMESTAMP     NOT NULL,
                         CONSTRAINT fk_pedido_cliente     FOREIGN KEY (cliente_id)     REFERENCES usuarios(id),
                         CONSTRAINT fk_pedido_restaurante FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
);

CREATE TABLE itens_pedido (
                              id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              pedido_id      NUMBER        NOT NULL,
                              produto_id     NUMBER        NOT NULL,
                              quantidade     NUMBER        NOT NULL,
                              preco_unitario NUMBER(10, 2) NOT NULL,
                              CONSTRAINT fk_item_pedido  FOREIGN KEY (pedido_id)  REFERENCES pedidos(id),
                              CONSTRAINT fk_item_produto FOREIGN KEY (produto_id) REFERENCES produtos(id)
);